### PR TITLE
Add ODE solver and examples

### PR DESCRIPTION
**Pull request by amartyamukherjee**
Modified the ODESolver module. Less epochs are required to achieve the same loss as the "ode" branch.
Added two examples to test the ODESolver class on: Lorenz63 and SEIR.

### CODE REVIEW

**Comment by amartyamukherjee** [comment]
Not ready for merge yet. "torchts/nn/models/ode.py" still needs to be cleaned.

**Comment by amartyamukherjee** [comment]
I need help, I'm not sure how to fix the following error in my Jupyter notebooks:
RuntimeError: Trying to backward through the graph a second time, but the saved intermediate results have already been freed. Specify retain_graph=True when calling backward the first time.

**Comment by amartyamukherjee** [comment]
Ready for code review!

**Comment by amartyamukherjee** [comment]
This branch is ready for code review

**Comment by amartyamukherjee** [comment]
@klane In my latest commit, I was able to reproduce the results in the "SEIR model with ODESolver.ipynb" notebook you added into your #57 branch. Since my modified class is compatible with both of our examples, would you be willing to close your pull request (#57) and review/merge this instead? Thanks.

**Comment by klane** [comment]
Thank you for your contribution @amartyamukherjee. We can certainly use this PR in favor of #57. Would you be able to add a few tests as well?

**Comment by amartyamukherjee** [comment]
@klane Thanks for letting me know. I just added some test cases. Hope it helps.

**Comment by amartyamukherjee** [comment]
@klane Happy holidays! Could I get an update on the code review process for this pull request?

**Comment by klane** [comment]
Thank you for reminding me @amartyamukherjee. I should be able to take a look this weekend. @droten can you review as well?

**Comment by amartyamukherjee** [comment]
@klane @droten @Rui1521 @yuqirose 
Hello, could I get an update on the code review for this PR? Thanks

**Comment by klane** [comment]
@amartyamukherjee I looked over the code, but I would like one of the other reviewers to have a look since I was not part of the model development.

**Comment by amartyamukherjee** [comment]
@klane Got it, thanks for the update!

**Comment by amartyamukherjee** [comment]
@klane Professor Rose Yu has let me know through email that this PR is ready to be merged. Could you merge this please?

**Comment by amartyamukherjee** [comment]
@klane I was wondering if there's a reason why this isn't merged yet? Thanks

**Comment by klane** [comment]
No reason @amartyamukherjee. I have just been trying to fix a few other things and have not gotten to it quite yet. I am going to make some small changes to ensure this is compatible with #190 before merging.

**Pull request merged**
